services:
  web:
    build: .
    command: poetry run daphne -b 0.0.0.0 -p 8000 main_hms.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: chat_db
    depends_on:
      - db
      - redis
      - elasticsearch
      - mongo
    volumes:
      - static_volume:/homeswap/static
      - ./main_hms/logs:/homeswap/main_hms/logs
      - ./media:/homeswap/media
    networks:
      - main_hms_network

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - main_hms_network

  celery:
    build: .
    command: poetry run celery -A main_hms worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - main_hms_network

  celery-beat:
    build: .
    command: poetry run celery -A main_hms beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - main_hms_network

  flower:
    build: .
    command: poetry run celery -A main_hms flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - celery
    networks:
      - main_hms_network

  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_hms_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/homeswap/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/homeswap/media
    depends_on:
      - web
    networks:
      - main_hms_network
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - main_hms_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./main_hms/logs:/homeswap/main_hms/logs
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - main_hms_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - main_hms_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - main_hms_network

volumes:
  postgres_data:
  static_volume:
  esdata01:
  media_volume:
  mongo-data:

networks:
  main_hms_network:
    driver: bridge
