services:
  web:
    build: .
    command: poetry run daphne -b 0.0.0.0 -p 8000 main_hms.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/homeswap/static

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: poetry run celery -A main_hms worker -l info
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: poetry run celery -A main_hms beat -l info
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - db

  flower:
    build: .
    command: poetry run celery -A main_hms flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - db
      - celery

  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/homeswap/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
