version: "3.7"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: poetry run daphne -b 0.0.0.0 -p 8000 main_hms.asgi:application
    volumes:
      - .:/homeswapd
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - celery
      - celery-beat

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: poetry run celery -A main_hms worker -l info
    volumes:
      - .:/homeswapd
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: poetry run celery -A main_hms beat -l info
    volumes:
      - .:/homeswapd
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  flower:
    build: .
    command: poetry run celery -A main_hms flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/homeswapd
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - celery

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
