# Generated by Django 4.2 on 2024-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, unique=True, verbose_name="Slug"
            ),
        ),
    ]
